### ISSUE TITLE
The polyfill example wont work in safari

### ISSUE THREAD

**Issue by kenchris** [WICG/WebOTP#21]
As Apple decided to never support extending any element but HTMLElement

**Comment by samuelgoto** [comment]
Ah, fair, agreed. I guess polyfill isn't the right word, because this isn't something that can be done purely in userland, but rather requires access to browser internals. 

The intent with the example here was to show that you **can** use the declarative API in a browser that only supports the imperative API (e.g. chrome, hence the use of the custom element) with some help from frameworks.

So, the following:

```html
<script src="framework.js"></script>
<input is="one-time-code" autocomplete="one-time-code">
```

Would work both in chrome (because the "is" custom element would use the imperative API) and safari (because the "is" would be ignored and the autocomplete="one-time-code" would take care of it too).

I'm going to rename the wording here from "polyfill" to "emulating" in the proposal and the spec text.

I hope this makes it clearer.

I'm going to resolve, unless there is any further clarification I can provide or anything you'd like me to act on.
